### PR TITLE
fix(main): fix loading metadata

### LINKED ISSUE #87: use hight level rootfs install cluster error
#### What happened:

use cluster images  `registry.cn-qingdao.aliyuncs.com/sealer-io/cloudrootfs:v1.19.9-alpha.1` install cluster

install host logger 
```
2021-05-13 17:10:40 [EROR] init master0 failed, error: [ssh][192.168.64.9]run command failed [kubeadm init --config=/var/lib/sealer/data/cloud-kernel/kubeadm-config.yaml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification], Process exited with status 1. Please clean and reinstall
```

in 192.168.64.9 exec found

```
root@sealer1:~# kubeadm init --config=/var/lib/sealer/data/cloud-kernel/kubeadm-config.yaml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification
W0513 17:13:30.271923   23615 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
this version of kubeadm only supports deploying clusters with the control plane version >= 1.18.0. Current version: v1.16.9
To see the stack trace of this error execute with --v=5 or higher
```

https://github.com/alibaba/sealer/blob/1c7b0e58f0b3c737e7dca25214c89108184a3362/runtime/init.go#L74 

we need fix it ,all images support version is v1.16.9 ,we read rootfs in cluster metadata info 

image

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cuisongliu**
### Does this pull request fix one issue?

Fixes #87

### CODE REVIEW

File: runtime/utils.go [hunk 1]
```diff
@@ -72,3 +73,62 @@ func PreInitMaster0(sshClient ssh.Interface, remoteHostIP string) error {
...
+
+	// case three : new major version > old major version +1;
+	// 1.18.2    1.16.10
+	if newMajor > major+1 {
+		return fmt.Errorf("kubernetes new version is bigger than current version, more than one major version is not allowed! New version: %s, current version: %s", new, old)
+	}
+	return nil
+}
+
+func For120(version string) bool {
```
Comment (fanux) [inline runtime/utils.go]: using VersionCompare to instead this?

Comment (cuisongliu) [reply runtime/utils.go]: I  already fix it

**Review by fanux — APPROVED** [review]
