### PR TITLE
fix: duplicated certSANS in generated kubeadm config file

### LINKED ISSUE #220: duplicated certSANs
generated kubeadm config file:
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.19.9
controlPlaneEndpoint: "apiserver.cluster.local:6443"
imageRepository: sea.hub:5000/library
networking:
  # dnsDomain: cluster.local
  podSubnet: 100.64.0.0/10
  serviceSubnet: 10.96.0.0/22
apiServer:
  certSANs:
  - 127.0.0.1
  - apiserver.cluster.local
  - 172.16.0.111
  - aliyun-inc.com
  - 10.0.0.2
  - 127.0.0.1
  - apiserver.cluster.local
  - 10.103.97.2
  - 172.16.0.111
  - 10.103.97.2
  extraArgs:
    etcd-servers: https://172.16.0.111:2379
    feature-gates: TTLAfterFinished=true,EphemeralContainers=true
    audit-policy-file: "/etc/kubernetes/audit-policy.yml"
    audit-log-path: "/var/log/kubernetes/audit.log"
    audit-log-format: json
    audit-log-maxbackup: '"10"'
    audit-log-maxsize: '"100"'
    audit-log-maxage: '"7"'
    enable-aggregator-routing: '"true"'
  extraVolumes:
  - name: "audit"
    hostPath: "/etc/kubernetes"
    mountPath: "/etc/kubernetes"
    pathType: DirectoryOrCreate
  - name: "audit-log"
    hostPath: "/var/log/kubernetes"
    mountPath: "/var/log/kubernetes"
    pathType: DirectoryOrCreate
  - name: localtime
    hostPath: /etc/localtime
    mountPath: /etc/localtime
    readOnly: true
    pathType: File
controllerManager:
  extraArgs:
    feature-gates: TTLAfterFinished=true,EphemeralContainers=true
    experimental-cluster-signing-duration: 876000h
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    readOnly: true
    pathType: File
scheduler:
  extraArgs:
    feature-gates: TTLAfterFinished=true,EphemeralContainers=true
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    readOnly: true
    pathType: File
etcd:
  local:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
```
certSANs field has replicated items.

### PR DESCRIPTION
**Pull request by ydcool**
### Describe what this PR does / why we need it

fix duplicated certSANS in generated kubeadm config file

### Does this pull request fix one issue?

Fixes #220 

### Describe how you did it

Using `utils.AppendIPList` to append all IP address into a single slice for `CertSANS` of env map, 
so we can prevent duplicated IP.

### CODE REVIEW

**Review by justadogistaken — DISMISSED** [review]
LGTM

File: runtime/kubeadm.go [hunk 1]
```diff
@@ -45,7 +45,13 @@ func (d *Default) templateFromContent(templateContent string) ([]byte, error) {
 	}
 
 	var envMap = make(map[string]interface{})
-	envMap[CertSANS] = d.APIServerCertSANs
+	sans := []string{"127.0.0.1"}
+	sans = utils.AppendIPList(sans, []string{d.APIServer})
+	sans = utils.AppendIPList(sans, d.Masters)
```
Comment (fanux) [inline runtime/kubeadm.go:50]: d.Masters maybe include port link this: 192.168.0.2:2202 need use utils.GetHostIPSlice(d.Masters)

**Comment by justadogistaken** [comment]
@ydcool Could you continue finishing this?

**Review by fanux — APPROVED** [review]
I will fixed it in other PR
