### PR TITLE
fix sealer rmi bug after tag

### LINKED ISSUE #91: sealer tag after rmi image
#### What happened:

```
sealer pull seadent/rootfs:latest
sealer tag seadent/rootfs:latest seadent/rootfs:aaaaa
sealer images

+----------------------------------+------------------------------------------------------------------------+
|             IMAGE ID             |                               IMAGE NAME                               |
+----------------------------------+------------------------------------------------------------------------+
| e4d64224c4c5a51e2a2064e120cada85 | seadent/rootfs:aaaaa                                                   |
+----------------------------------+------------------------------------------------------------------------+

sealer rmi seadent/rootfs:aaaaa 

2021-05-13 22:03:51 [EROR] e4d64224c4c5a51e2a2064e120cada85.yaml parsing failed, open /var/lib/sealer/metadata/e4d64224c4c5a51e2a2064e120cada85.yaml: no such file or directory


```

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by touchuyht**
### Does this pull request fix one issue?

Fixes #91
### Describe how you did it
Delete corresponding record in images_metadata.json if the image metadata yaml is missing. Delete image records which is generated after sealer tag.

### CODE REVIEW

File: image/default_image.go [hunk 1]
```diff
@@ -135,7 +135,13 @@ func (d DefaultImageService) Delete(imageName string) error {
 
 	image, err = imageutils.GetImage(named.Raw())
```
Comment (justadogistaken) [inline image/default_image.go:136]: sealer images get images from images_metadata.json first, I guess we can check image existence from imageMetadataMap

File: image/utils/meta_image.go [hunk 2]
```diff
@@ -45,11 +45,17 @@ func DeleteImage(imageName string) error {
...
 	}
 
-	_, ok := imagesMap[imageName]
+	imageMetadata, ok := imagesMap[imageName]
 	if !ok {
 		return nil
 	}
 	delete(imagesMap, imageName)
+	// delete image name alias records
+	for imageName, value := range imagesMap {
```
Comment (justadogistaken) [inline image/utils/meta_image.go:54]: should we delete all images with same id?

**Comment by fanux** [comment]
seautil don't need have rmi command. seautil is for command proxy witch os don't have, like ipvs or cert generator.

File: image/utils/meta_image.go (hunk 2 above)
Comment (fanux) [reply image/utils/meta_image.go:54]: same as docker rmi is fine

File: image/base_image_manager.go [hunk 3]
```diff
@@ -46,29 +45,8 @@ func (bim BaseImageManager) syncImageLocal(image v1.Image) (err error) {
...
 
 func (bim BaseImageManager) deleteImageLocal(imageName, imageID string) (err error) {
-	// Read image metadata from file to ensure that if we fail to delete image records,
-	// the image metadata can be recovered from it.
-	image, err := imageutils.GetImage(imageName)
-	if err != nil {
-		return err
-	}
-
 	err = deleteImage(imageID)
```
Comment (justadogistaken) [inline image/base_image_manager.go:48]: fast return , return deleteImage(imageID)

File: image/default_image.go [hunk 4]
```diff
@@ -125,45 +125,71 @@ func (d DefaultImageService) Login(RegistryURL, RegistryUsername, RegistryPasswd
...
-
-	imageMetadataMap, err := imageutils.GetImageMetadataMap()
+	imageMetadata, ok := imageMetadataMap[named.Raw()]
+	if !ok {
+		return fmt.Errorf("failed to find image with name %s", imageName)
+	}
+	err = imageutils.DeleteImage(imageName)
 	if err != nil {
-		return err
+		return fmt.Errorf("failed to untag image %s", imageName)
```
Comment (justadogistaken) [inline image/default_image.go:147]: we'd better wrap the err. failed to untag image %s, err: %s

File: image/default_image.go [hunk 5]
```diff
@@ -125,45 +125,71 @@ func (d DefaultImageService) Login(RegistryURL, RegistryUsername, RegistryPasswd
...
-		if imageMetadata.ID == "" {
-			continue
-		}
-		tmpImage, err := imageutils.GetImageByID(imageMetadata.ID)
-		if err != nil {
+	logger.Info("untag image %s succeeded", imageName)
+
+	for _, value := range imageMetadataMap {
+		switch value.ID {
+		case "":
```
Comment (justadogistaken) [inline image/default_image.go:153]: I guess. "if imageMetadata.ID == value.ID is fine"

File: image/base_image_manager.go [hunk 6]
```diff
@@ -46,29 +45,7 @@ func (bim BaseImageManager) syncImageLocal(image v1.Image) (err error) {
 }
 
 func (bim BaseImageManager) deleteImageLocal(imageName, imageID string) (err error) {
```
Comment (justadogistaken) [inline image/base_image_manager.go:47]: is imageName useless?

File: image/default_image.go [hunk 7]
```diff
@@ -125,45 +125,68 @@ func (d DefaultImageService) Login(RegistryURL, RegistryUsername, RegistryPasswd
...
+			if imageTagCount > 1 {
+				break
+			}
+		}
+	}
+	if imageTagCount != 1 {
+		return nil
+	}
+
+	image, err = imageutils.GetImageByID(imageMetadata.ID)
```
Comment (justadogistaken) [inline image/default_image.go:163]: what is the point for getting image? imageName and imageId are in imageMetadata already.

File: image/default_image.go [hunk 8]
```diff
@@ -125,45 +125,68 @@ func (d DefaultImageService) Login(RegistryURL, RegistryUsername, RegistryPasswd
...
+	if err != nil {
+		return fmt.Errorf("failed to find image metadata, err: %v", err)
+	}
```
Comment (justadogistaken) [inline image/default_image.go:166]: I guess it would be better to put image metadata existence validation within fun deleteImage

File: image/default_image.go [hunk 9]
```diff
@@ -125,45 +125,68 @@ func (d DefaultImageService) Login(RegistryURL, RegistryUsername, RegistryPasswd
...
-		if err != nil {
-			continue
+
+	for _, value := range imageMetadataMap {
+		if value.ID != imageMetadata.ID {
+			tmpImage, err := imageutils.GetImageByID(imageMetadata.ID)
+			if err != nil {
+				continue
+			}
+			images = append(images, tmpImage)
```
Comment (justadogistaken) [inline image/default_image.go:179]: I suppose that the operation could be put in last "for _, value := range imageMetadataMap", or you can name here a   func "getImageMap? or something ?"

File: image/default_image.go (hunk 7 above)
Comment (touchuyht) [reply image/default_image.go:163]: It need image's detailed content which was saved in image yaml to delete a image.

File: image/default_image.go (hunk 8 above)
Comment (touchuyht) [reply image/default_image.go:178]: There is actually already an image existence validation procedure in the deleteImage function.

File: image/base_image_manager.go (hunk 6 above)
Comment (touchuyht) [reply image/base_image_manager.go]: Already deleted it.

**Review by fanux — APPROVED** [review]
